language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - 'node'
script: echo 'skipping test'
jobs:
  include:
    - stage: lint
      script: 'npm run eslint'
    - stage: release
      node_js: 10
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
